spring:
  mustache:
    suffix: .html
  profiles:
    active: stomp

  datasource:
    url: jdbc:mysql://yoyo.cgenyk496gbx.us-east-1.rds.amazonaws.com:3306/yoyo?serverTimezone=UTC&characterEncoding=UTF-8
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace




